version: '3.8'

services:
  todo_list_app:
    image: todolist:0.0.1
    ports:
      - 9090:8080
    environment:
      DB_URL: "jdbc:postgresql://db:5432/todolist"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "123456"
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 9092:5432